// GENERATED by veq.py from the PDK liberty `function :` attributes.
// Source: sg13g2_stdcell_typ_1p20V_25C.lib

module sg13g2_inv_1 (A, Y);
  input A;
  output Y;
  assign Y = ~ ( A );
endmodule

module sg13g2_buf_1 (A, X);
  input A;
  output X;
  assign X = A;
endmodule

module sg13g2_nand2_1 (A, B, Y);
  input A, B;
  output Y;
  assign Y = ~ ( A & B );
endmodule

module sg13g2_nor2_1 (A, B, Y);
  input A, B;
  output Y;
  assign Y = ~ ( A | B );
endmodule

module sg13g2_and2_1 (A, B, X);
  input A, B;
  output X;
  assign X = ( A & B );
endmodule

module sg13g2_or2_1 (A, B, X);
  input A, B;
  output X;
  assign X = ( A | B );
endmodule

module sg13g2_xor2_1 (A, B, X);
  input A, B;
  output X;
  assign X = ( A ^ B );
endmodule

module sg13g2_xnor2_1 (A, B, Y);
  input A, B;
  output Y;
  assign Y = ~ ( A ^ B );
endmodule

module sg13g2_nor2b_1 (A, B_N, Y);
  input A, B_N;
  output Y;
  assign Y = ~ ( A | ~ B_N );
endmodule

module sg13g2_nand2b_1 (A_N, B, Y);
  input A_N, B;
  output Y;
  assign Y = ~ ( ~ A_N & B );
endmodule

module sg13g2_mux2_1 (A0, A1, S, X);
  input A0, A1, S;
  output X;
  assign X = ( ~ S & A0 ) | ( S & A1 );
endmodule

module sg13g2_a21oi_1 (A1, A2, B1, Y);
  input A1, A2, B1;
  output Y;
  assign Y = ~ ( ( A1 & A2 ) | B1 );
endmodule

module sg13g2_a21o_1 (A1, A2, B1, X);
  input A1, A2, B1;
  output X;
  assign X = ( ( A1 & A2 ) | B1 );
endmodule

module sg13g2_o21ai_1 (A1, A2, B1, Y);
  input A1, A2, B1;
  output Y;
  assign Y = ~ ( ( A1 | A2 ) & B1 );
endmodule

module sg13g2_tiehi (L_HI);
  output L_HI;
  assign L_HI = 1;
endmodule

module sg13g2_tielo (L_LO);
  output L_LO;
  assign L_LO = 0;
endmodule

module pg_xor2 (A, B, X);  input A, B; output X; assign X = A ^ B; endmodule
module pg_xnor2 (A, B, Y); input A, B; output Y; assign Y = ~(A ^ B); endmodule
module pg_mux2 (A0, A1, S, X); input A0, A1, S; output X;
  assign X = S ? A1 : A0;
endmodule

