#!/usr/bin/env python3
"""(c) INDEPENDENT EQUIVALENCE RE-CHECK of the Phase-2 remap.

Independence, stated plainly:
  * cell Boolean models are GENERATED from the PDK liberty file's own
    `function :` attributes (libfun.py), NOT read from the run's minicells.v.
    The run's minicells.v is then diffed against mine as a separate check.
  * the pass-gate cells pg_xor2/pg_xnor2/pg_mux2 are written here from their
    NAME semantics and cross-checked against the PDK cells they replace.
  * the golden is a pure-Python model of the RTL equations in sha_slice.v,
    written here, plus yosys' own RTL elaboration for the SAT miter.
  * SAT miter (E1) and equiv_induct (E2) are run by me, on the netlists the
    run produced, with my models.
  * the vector run (E3) uses iverilog with my models.
"""
import json, os, re, subprocess, sys, time
from libfun import cells, lib_to_verilog

HERE = os.path.dirname(os.path.abspath(__file__))
P2 = "/usr/local/src/stat-sim/qal/pgcell/p2"
OUT = os.path.join(P2, "out")
RTL = "/usr/local/src/stat-sim/qal/synth/threeway/sha_slice.v"
CMOS = "/usr/local/src/stat-sim/qal/synth/threeway/work/sha_slice.cmos.v"
YOSYS = "/home/claude/.local/bin/yosys"
IVL = "/usr/local/bin/iverilog"
VVP = "/usr/local/bin/vvp"

CELLS_WANT = ["sg13g2_inv_1", "sg13g2_buf_1", "sg13g2_nand2_1", "sg13g2_nor2_1",
              "sg13g2_and2_1", "sg13g2_or2_1", "sg13g2_xor2_1", "sg13g2_xnor2_1",
              "sg13g2_nor2b_1", "sg13g2_nand2b_1", "sg13g2_mux2_1",
              "sg13g2_a21oi_1", "sg13g2_a21o_1", "sg13g2_o21ai_1",
              "sg13g2_o21a_1", "sg13g2_tiehi", "sg13g2_tielo"]


def gen_models():
    """cell models straight out of the PDK liberty functions"""
    C = cells()
    lines = ["// GENERATED by veq.py from the PDK liberty `function :` attributes.",
             "// Source: sg13g2_stdcell_typ_1p20V_25C.lib", ""]
    fun = {}
    for c in CELLS_WANT:
        if c not in C:
            continue
        order, pins = C[c]
        ins = [p for p in order if pins[p][1] is None]
        outs = [p for p in order if pins[p][1] is not None]
        ports = ins + outs
        lines.append("module %s (%s);" % (c, ", ".join(ports)))
        if ins:
            lines.append("  input %s;" % ", ".join(ins))
        for o in outs:
            lines.append("  output %s;" % o)
            v = lib_to_verilog(pins[o][1])
            lines.append("  assign %s = %s;" % (o, v))
            fun[(c, o)] = (ins, pins[o][1], v)
        lines.append("endmodule\n")
    # pass-gate cells: written from their NAME semantics, cross-checked below
    lines += [
        "module pg_xor2 (A, B, X);  input A, B; output X; assign X = A ^ B; endmodule",
        "module pg_xnor2 (A, B, Y); input A, B; output Y; assign Y = ~(A ^ B); endmodule",
        "module pg_mux2 (A0, A1, S, X); input A0, A1, S; output X;",
        "  assign X = S ? A1 : A0;",
        "endmodule", ""]
    p = os.path.join(HERE, "mycells.v")
    open(p, "w").write("\n".join(lines) + "\n")
    return p, fun


def crosscheck_pg(fun):
    """pg_* must be Boolean-identical to the PDK cells they stand in for."""
    import itertools
    r = {}
    # pg_xor2 vs sg13g2_xor2_1 ; pg_xnor2 vs sg13g2_xnor2_1
    for pg, pdk, f in (("pg_xor2", "sg13g2_xor2_1", lambda a, b: a ^ b),
                       ("pg_xnor2", "sg13g2_xnor2_1", lambda a, b: 1 - (a ^ b))):
        ins, expr, _ = fun[(pdk, "X" if "xor2" in pdk else "Y")]
        ok = True
        for a, b in itertools.product((0, 1), repeat=2):
            env = dict(zip(ins, (a, b)))
            ok &= (evallib(expr, env) == f(a, b))
        r[pg] = dict(vs=pdk, identical=bool(ok))
    ins, expr, _ = fun[("sg13g2_mux2_1", "X")]
    ok = True
    for a0, a1, s in itertools.product((0, 1), repeat=3):
        env = dict(A0=a0, A1=a1, S=s)
        ok &= (evallib(expr, env) == (a1 if s else a0))
    r["pg_mux2"] = dict(vs="sg13g2_mux2_1", identical=bool(ok))
    return r


def evallib(expr, env):
    v = lib_to_verilog(expr)
    py = v.replace('~', ' not ').replace('&', ' and ').replace('|', ' or ')
    # xor has no short python word form at this precedence; use !=
    py = re.sub(r'\^', ' != ', py)
    return int(bool(eval(py, {}, {k: bool(x) for k, x in env.items()})))


# ---------------------------------------------------------------- golden
def golden(a, b, c, e, f, g):
    """pure-Python model of the RTL in sha_slice.v, written here"""
    M = 0xFF
    maj = ((a & b) ^ (a & c) ^ (b & c)) & M
    ch = ((e & f) ^ ((~e) & g)) & M
    s = (a + b) & M
    return maj, ch, s


def sh(cmd, cwd=HERE, timeout=900):
    r = subprocess.run(cmd, shell=True, capture_output=True, text=True,
                       cwd=cwd, timeout=timeout)
    return r.returncode, r.stdout + r.stderr


# ------------------------------------------------------------- E1 / E2
def formal(name, netlist, models, top="sha_slice"):
    """Two independent engines.  gold and gate are each elaborated in their OWN
    yosys process to RTLIL, then combined -- so a name collision cannot silently
    make one side stand in for the other (my first draft did exactly that and
    yosys refused with 'Re-definition of module'; it failed loudly)."""
    res = {}
    gold = os.path.join(HERE, "g_%s_gold.il" % name)
    gate = os.path.join(HERE, "g_%s_gate.il" % name)
    pre = [("gold", """
read_verilog -sv %s
hierarchy -top %s
proc; opt -full; flatten; opt -full
rename %s gold
write_rtlil %s
""" % (RTL, top, top, gold)),
           ("gate", """
read_verilog %s
read_verilog %s
hierarchy -top %s
proc; flatten; opt -full
rename %s gate
write_rtlil %s
""" % (models, netlist, top, top, gate))]
    for tag, ys in pre:
        p = os.path.join(HERE, "pre_%s_%s.ys" % (tag, name))
        open(p, "w").write(ys)
        rc, out = sh("%s -s %s" % (YOSYS, p))
        open(os.path.join(HERE, "pre_%s_%s.log" % (tag, name)), "w").write(out)
        if rc != 0:
            return {"E1_sat": dict(rc=rc, pass_=False, tail=out[-500:]),
                    "E2_induct": dict(rc=rc, pass_=False, tail="elab failed")}
    scripts = {
        "E1_sat": """
read_rtlil %s
read_rtlil %s
miter -equiv -flatten -make_assert gold gate miter
hierarchy -top miter
sat -verify -prove-asserts -show-ports miter
""" % (gold, gate),
        "E2_induct": """
read_rtlil %s
read_rtlil %s
equiv_make gold gate equiv
hierarchy -top equiv
equiv_simple
equiv_induct
equiv_status -assert
""" % (gold, gate)}
    for tag, ys in scripts.items():
        p = os.path.join(HERE, "%s_%s.ys" % (tag, name))
        open(p, "w").write(ys)
        rc, out = sh("%s -s %s" % (YOSYS, p))
        open(os.path.join(HERE, "%s_%s.log" % (tag, name)), "w").write(out)
        ok = (rc == 0)
        if tag == "E1_sat":
            ok = ok and "SUCCESS" in out and "FAIL" not in out
        else:
            ok = ok and "Equivalence successfully proven" in out
        res[tag] = dict(rc=rc, pass_=bool(ok), tail=out[-500:])
    return res


# ------------------------------------------------------------------ E3
TB = r"""
`timescale 1ns/1ps
module tb;
  reg [7:0] a,b,c,e,f,g;
  wire [7:0] maj,ch,sum;
  integer i, mism, n;
  reg [31:0] lf;
  reg [7:0] emaj, ech, esum;
  sha_slice U(.a(a),.b(b),.c(c),.e(e),.f(f),.g(g),.maj(maj),.ch(ch),.sum(sum));
  task chk; begin
    emaj = (a&b)^(a&c)^(b&c); ech = (e&f)^((~e)&g); esum = a+b; n = n+1;
    #1;
    if (maj!==emaj || ch!==ech || sum!==esum) begin
      mism = mism+1;
      if (mism < 6) $display("MISM a=%h b=%h c=%h e=%h f=%h g=%h  maj=%h/%h ch=%h/%h sum=%h/%h",
                              a,b,c,e,f,g,maj,emaj,ch,ech,sum,esum);
    end
  end endtask
  function [31:0] nxt; input [31:0] s; begin
    nxt = {s[30:0], s[31]^s[21]^s[1]^s[0]};
  end endfunction
  initial begin
    mism=0; n=0; lf=32'hACE1_2345;
    // 1. EXHAUSTIVE over all 65536 (a,b) pairs -> the 8-bit CPA is COMPLETE
    for (i=0;i<65536;i=i+1) begin
      a = i[15:8]; b = i[7:0];
      c = lf[7:0]; e = lf[15:8]; f = lf[23:16]; g = lf[31:24];
      chk; lf = nxt(lf);
    end
    // 2. EXHAUSTIVE per-bit maj: all 8 (a,b,c) bit patterns on every bit at once,
    //    walked so every bit sees all 8
    for (i=0;i<256;i=i+1) begin
      a = {8{i[0]}}; b = {8{i[1]}}; c = {8{i[2]}};
      e = i[7:0]; f = ~i[7:0]; g = i[7:0] ^ 8'h5A; chk;
      a = i[7:0]; b = ~i[7:0]; c = i[7:0]^8'h3C;
      e = {8{i[0]}}; f = {8{i[1]}}; g = {8{i[2]}}; chk;
    end
    // 3. EXHAUSTIVE per-bit ch: all 8 (e,f,g) patterns
    for (i=0;i<8;i=i+1) begin
      e={8{i[0]}}; f={8{i[1]}}; g={8{i[2]}};
      a=8'h5A; b=8'hA5; c=8'h3C; chk;
    end
    // 4. random
    for (i=0;i<90000;i=i+1) begin
      a=lf[7:0]; lf=nxt(lf); b=lf[7:0]; lf=nxt(lf); c=lf[7:0]; lf=nxt(lf);
      e=lf[7:0]; lf=nxt(lf); f=lf[7:0]; lf=nxt(lf); g=lf[7:0]; lf=nxt(lf);
      chk;
    end
    $display("VECTORS %0d MISMATCH %0d", n, mism);
    $finish;
  end
endmodule
"""


def vectors(name, netlist, models):
    tb = os.path.join(HERE, "tb_%s.v" % name)
    open(tb, "w").write(TB)
    sim = os.path.join(HERE, "sim_%s" % name)
    rc, out = sh("%s -g2005 -o %s %s %s %s" % (IVL, sim, tb, models, netlist))
    if rc != 0:
        return dict(compiled=False, log=out[-600:])
    rc, out = sh("%s %s" % (VVP, sim))
    m = re.search(r"VECTORS (\d+) MISMATCH (\d+)", out)
    return dict(compiled=True, vectors=int(m.group(1)) if m else None,
                mismatches=int(m.group(2)) if m else None,
                pass_=bool(m and int(m.group(2)) == 0), log=out[-600:])


if __name__ == "__main__":
    models, fun = gen_models()
    R = dict(models=models, when=time.strftime("%F %T"))
    R["pg_crosscheck"] = crosscheck_pg(fun)
    # diff my generated models against the run's minicells.v, function by function
    R["minicells_agreement"] = {}
    mini = open(os.path.join(P2, "minicells.v")).read()
    for c in CELLS_WANT:
        m = re.search(r"module %s\s*\(([^)]*)\).*?assign (\w+) = ([^;]+);" % c,
                      mini, re.S)
        R["minicells_agreement"][c] = (m.group(3).strip() if m else None)

    nets = sys.argv[1:] or ["cmos", "pgp", "pgp1", "pgp1c", "pgp2", "pgp2c",
                            "pgr1", "pgr1c", "abc_nand_resyn2", "abc_pg_resyn2"]
    R["netlists"] = {}
    for n in nets:
        net = CMOS if n == "cmos" else os.path.join(OUT, "sha_slice.%s.v" % n)
        if not os.path.exists(net):
            R["netlists"][n] = dict(error="missing %s" % net)
            continue
        t0 = time.monotonic()
        d = dict(path=net)
        d.update(formal(n, net, models))
        d["E3_vectors"] = vectors(n, net, models)
        d["wall_s"] = round(time.monotonic() - t0, 1)
        d["PASS"] = bool(d["E1_sat"]["pass_"] and d["E2_induct"]["pass_"]
                         and d["E3_vectors"].get("pass_"))
        R["netlists"][n] = d
        print("%-18s E1=%s E2=%s E3=%s/%s  %.0fs" %
              (n, d["E1_sat"]["pass_"], d["E2_induct"]["pass_"],
               d["E3_vectors"].get("vectors"), d["E3_vectors"].get("mismatches"),
               d["wall_s"]), flush=True)
    json.dump(R, open(os.path.join(HERE, "VEQ.json"), "w"), indent=1)
    print("wrote VEQ.json")
