#!/usr/bin/env python3
"""Generate VACASK model cards for sg13g2 PSP103 from the kestrel SPICE .lib.

Source of truth: /usr/local/src/kestrel/sim/models/sg13g2_psp103_tt.lib —
the exact card the committed Xyce anchors used. Parameters are copied
VERBATIM; the only edits are the two the engines themselves impose:
  * level=103 dropped (VACASK selects the model by master name psp103va);
  * type=1 / type=-1 added (Xyce infers it from the nmos/pmos card type);
  * the 10 parameters the Xyce anchor runs THEMSELVES ignored (printed
    "No model parameter X found ... parameter ignored" in the committed
    campaign logs, e.g. qal/skept/i0.log) are dropped so both engines see
    the identical effective parameter set:
      ctbo ctgo dta munqso nsubedgelexp st2vfbo stcto stthecso swnqs thecso
    (values in the card: dta=0, swnqs=0 — the rest are PSP>=103.6 stress/NQS
    params foreign to the 103.4 module both engines compile).
"""
import re, sys

LIB = "/usr/local/src/kestrel/sim/models/sg13g2_psp103_tt.lib"
DROP = {"level", "ctbo", "ctgo", "dta", "munqso", "nsubedgelexp",
        "st2vfbo", "stcto", "stthecso", "swnqs", "thecso"}

def parse(lib_text):
    cards, cur = {}, None
    for ln in lib_text.splitlines():
        s = ln.strip()
        if s.lower().startswith(".model"):
            t = s.split()
            cur = (t[1].lower(), t[2].lower())          # (name, nmos/pmos)
            cards[cur] = []
            s = " ".join(t[3:])
        elif s.startswith("+") and cur:
            s = s[1:]
        elif cur:
            continue
        else:
            continue
        for m in re.finditer(r"([A-Za-z0-9_]+)\s*=\s*([-+0-9.eE]+)", s):
            k, v = m.group(1).lower(), m.group(2)
            if k in DROP:
                continue
            cards[cur].append((k, v))
    return cards

def emit(cards, out):
    w = open(out, "w")
    w.write("// GENERATED by gen_models_sg13g2.py from %s\n" % LIB)
    w.write("// Verbatim parameter copy; see header of the generator for the\n")
    w.write("// three mechanical edits (level, type, the 10 Xyce-ignored params).\n\n")
    for (name, kind), kv in cards.items():
        w.write("model %s psp103va (\n" % name)
        w.write("    type=%d\n" % (1 if kind == "nmos" else -1))
        for k, v in kv:
            w.write("    %s=%s\n" % (k, v))
        w.write(")\n\n")
    w.close()
    print("wrote %s: %s" % (out, {n: len(kv) for (n, _), kv in cards.items()}))

if __name__ == "__main__":
    cards = parse(open(LIB).read())
    emit(cards, sys.argv[1] if len(sys.argv) > 1 else "sg13g2_models.inc")
