#!/usr/bin/env python3
"""qal/cipher/p2/cmosnat.py -- the CMOS-NATIVE implementation of the SAME
functions, and the two-sided comparison it makes possible.

There are TWO honest CMOS comparators and they answer different questions.  Both
are reported, exactly as Phase 1 reported both its fixed-tank and its
rail-matched-tank pairs.

  SAME-NETLIST  (gate G9 strict).  The identical Chain -- identical cells,
      identical CLOAD, identical wire, identical .OPTIONS, identical edges,
      FORWARDING CELLS AND ALL -- on an ideal supply set to the QAL row's own
      measured delivered rail peak.  Only the supply differs, so this isolates
      the TECHNOLOGY at a fixed netlist.  It is generated by cg.cmos_deck() from
      the same Chain object, so symmetry is structural rather than promised.

  CMOS-NATIVE.  The same FUNCTION built the way CMOS would actually build it: a
      flat combinational netlist with NO forwarding cells, because a static gate
      holds its output against a supply that never goes away.  This is the
      implementation an engineer would ship, so the ratio computed against it is
      the real one -- and it favours CMOS further, which makes every QAL ratio
      reported against it conservative for QAL.

The gap between the two IS the forwarding tax, measured rather than asserted.
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import cg
from cg import CELLS, cell_devices, CLOAD, EDGE, LAG_PS, TAIL, integ, head_lines


class Flat(object):
    """A flat combinational netlist: no levels, no forwarding, topological order."""

    def __init__(self, name):
        self.name = name
        self.cells = []          # (kind, out, [ins], sig)
        self.sources = {}        # net -> bool
        self.val = {}            # net -> bool
        self.wire = {}           # out net -> Cw fF

    def src(self, tag, v):
        n = "s_" + tag
        self.sources[n] = bool(v)
        self.val[n] = bool(v)
        return n

    def emit(self, kind, ins, sig=None):
        out = "n%d" % len(self.cells)
        av = [self.val[i] for i in ins]
        if len(av) != CELLS[kind][1]:
            raise SystemExit("%s: %s wants %d inputs" % (self.name, kind,
                                                         CELLS[kind][1]))
        self.val[out] = bool(CELLS[kind][2](av))
        self.cells.append((kind, out, list(ins), sig or out))
        return out

    def devices(self):
        return sum(cell_devices(k) for k, _, _, _ in self.cells)

    def eval_toggled(self, toggle):
        """Output values with only the sources in `toggle` complemented.

        AMENDMENT B10a.  My first full-cycle stimulus complemented EVERY held
        source -- and complementing BOTH operands of an XOR leaves its output
        unchanged, so on an XOR-dominated datapath the stimulus switched
        nothing.  The measured delay came out as 0.0 ps for a 32-cell XOR level
        and the measured charge never touched the output nodes or the wire hung
        on them, which is the entire quantity Phase 2 exists to measure.

        Toggling ONE operand word instead flips every XOR output.
        """
        v = {n: ((not b) if n in toggle else b)
             for n, b in self.sources.items()}
        for kind, out, ins, sig in self.cells:
            v[out] = bool(CELLS[kind][2]([v[i] for i in ins]))
        return v

    def activity(self, toggle):
        """The fraction of OUTPUT nets that actually change on this event.

        This matters for the comparison and is reported, not hidden: a QAL beat
        raises and returns the whole bank rail whatever the data does, so its
        energy is activity-INDEPENDENT, while a CMOS transition charges only the
        nodes that flip, so its energy scales with activity.  Toggling a whole
        operand word flips every XOR output, i.e. activity 1.0, which is the
        WORST case for CMOS and therefore CONSERVATIVE for QAL.
        """
        v = self.eval_toggled(toggle)
        n = len(self.cells)
        ch = sum(1 for kind, out, ins, sig in self.cells
                 if bool(v[out]) != bool(self.val[out]))
        return dict(cells=n, cells_changing=ch,
                    activity=round(ch / float(n), 4) if n else 0.0,
                    outputs=len(self.outputs),
                    outputs_changing=sum(1 for o in self.outputs
                                         if bool(v[o]) != bool(self.val[o])))

    def census(self):
        kinds = {}
        for k, _, _, _ in self.cells:
            kinds[k] = kinds.get(k, 0) + 1
        # DERIVED: the longest path in gate levels, which is the CMOS critical
        # path in units of gate delays (not a time -- the time is MEASURED).
        depth = {}
        for n in self.sources:
            depth[n] = 0
        for k, out, ins, _ in self.cells:
            depth[out] = 1 + max(depth[i] for i in ins)
        return dict(name=self.name, cells=len(self.cells), devices=self.devices(),
                    kinds=kinds, gate_depth_DERIVED=max(depth.values()),
                    n_sources=len(self.sources),
                    wire_nets=len([1 for v in self.wire.values() if v > 0]),
                    wire_total_fF=round(sum(self.wire.values()), 4))


# ------------------------------------------------------------------ adders
def cmos_adder(W, form, cw_per_bit=0.0, seed=0x9E37):
    """The SAME adder function, CMOS-native.  Identical input vector to
    veh.build_adder so the reference sum is the same number."""
    a_val = [(seed >> (i % 16)) & 1 for i in range(W)]
    b_val = [((seed * 3 + 0x5A5A) >> (i % 16)) & 1 for i in range(W)]
    for i in range(1, min(W, 6)):
        a_val[i], b_val[i] = 1, 0
    a_val[0], b_val[0] = 1, 1

    F = Flat("cmos_%s_w%d" % (form, W))
    A = [F.src("a%d" % i, a_val[i]) for i in range(W)]
    Bw = [F.src("b%d" % i, b_val[i]) for i in range(W)]

    p = [F.emit("xor2", [A[i], Bw[i]], "p%d" % i) for i in range(W)]
    g = [F.emit("and2", [A[i], Bw[i]], "g%d" % i) for i in range(W)]

    if form == "ripple":
        # c_{i+1} = G_i | (P_i & c_i).  a21o is the AO21 the PDK ships.
        c = [None] * W
        c[0] = g[0]
        for i in range(1, W):
            c[i] = F.emit("a21o", [p[i], c[i - 1], g[i]], "c%d" % i)
        carry = c
    elif form == "ks":
        # the same alternating-polarity prefix, but with NO forwarding: a cell
        # only exists where there is a partner, and a signal that has no cell at
        # a stage simply keeps its old net.
        import math
        G, P, pol = list(g), list(p), True
        nstage = int(math.ceil(math.log(W, 2)))
        for st in range(1, nstage + 1):
            s = 1 << (st - 1)
            nG, nP = list(G), list(P)
            for i in range(W):
                if i >= s:
                    if pol:
                        nG[i] = F.emit("a21oi", [P[i], G[i - s], G[i]])
                        if st < nstage:
                            nP[i] = F.emit("nand2", [P[i], P[i - s]])
                    else:
                        nG[i] = F.emit("o21ai", [P[i], G[i - s], G[i]])
                        if st < nstage:
                            nP[i] = F.emit("nor2", [P[i], P[i - s]])
                else:
                    # NO CELL.  In CMOS the value simply stays on its net.  This
                    # is the line of code that is the whole difference.
                    pass
            # a bit with no partner keeps the PREVIOUS polarity while its
            # partnered neighbours have flipped, so it must be re-polarised --
            # in CMOS that is one inverter, and only for i < s, not for every
            # bit at every level.
            for i in range(W):
                if i < s:
                    nG[i] = F.emit("inv", [G[i]])
                    if st < nstage:
                        nP[i] = F.emit("inv", [P[i]])
            G, P = nG, nP
            pol = not pol
        carry = G
    else:
        raise SystemExit("form?")

    av = sum(a_val[i] << i for i in range(W))
    bv = sum(b_val[i] << i for i in range(W))
    sv = (av + bv) & ((1 << W) - 1)

    # The sum cell must match the CARRY's polarity.  In the QAL build the bit
    # propagate is FORWARDED through the prefix tree and so flips once per
    # level, arriving with the same polarity as the carry; in CMOS it is NOT
    # forwarded -- it sits on its original net and stays TRUE while the carry has
    # flipped once per prefix stage.  So the two technologies need DIFFERENT sum
    # cells for the identical function, which is a consequence of the forwarding
    # difference and not a free choice.
    outs = [p[0]]
    for i in range(1, W):
        want_s = bool((sv >> i) & 1)
        true_c = bool(want_s) != bool(F.val[p[i]])      # c_in = s XOR p
        carry_is_true = (F.val[carry[i - 1]] == true_c)
        kind = "xor2" if carry_is_true else "xnor2"
        outs.append(F.emit(kind, [p[i], carry[i - 1]], "s%d" % i))
    got = sum((1 if F.val[outs[i]] else 0) << i for i in range(W))
    F.outputs = outs
    F.toggle = set("s_b%d" % i for i in range(W))    # toggle operand B
    F.reference = dict(a=av, b=bv, want=sv, got=got, MATCH=(got == sv))
    if cw_per_bit > 0.0:
        for k, out, ins, sig in F.cells:
            F.wire[out] = cw_per_bit
    return F


def cmos_addroundkey(cw_per_bit=0.0):
    """AddRoundKey CMOS-native: 128 XOR2 and nothing else.  ShiftRows is wiring
    in BOTH technologies -- that part of the insight is true and is not
    disputed."""
    import veh
    st, rk = veh.aes_sbox_free_state()
    sb = [(st[i] >> b) & 1 for i in range(16) for b in range(8)]
    kb = [(rk[i] >> b) & 1 for i in range(16) for b in range(8)]
    F = Flat("cmos_addroundkey")
    outs = []
    for j in range(128):
        s = F.src("st%d" % j, sb[j])
        k = F.src("rk%d" % j, kb[j])
        outs.append(F.emit("xor2", [s, k], "y%d" % j))
    ark = [st[i] ^ rk[i] for i in range(16)]
    want = [(ark[i] >> b) & 1 for i in range(16) for b in range(8)]
    got = [1 if F.val[o] else 0 for o in outs]
    F.outputs = outs
    F.toggle = set("s_rk%d" % j for j in range(128))   # toggle the round key
    F.reference = dict(addroundkey=[hex(x) for x in ark],
                       MATCH=(got == want))
    if cw_per_bit > 0.0:
        for j, o in enumerate(outs):
            F.wire[o] = cw_per_bit
    return F


def cmos_qr_xor(W=32, r=16, cw_at_mean=0.0):
    """The CMOS-native form of one ChaCha (xor, rotate) step: W xor2 cells and
    nothing else.  The rotate is wiring in BOTH technologies."""
    import veh
    D0, A0 = 0x243F6A88, 0x85A308D3
    F = Flat("cmos_qrxor_w%d_r%d" % (W, r))
    d = [F.src("d%d" % i, (D0 >> i) & 1) for i in range(W)]
    a = [F.src("a%d" % i, (A0 >> i) & 1) for i in range(W)]
    outs = []
    mean = 2.0 * r * (W - r) / float(W)
    for j in range(W):
        k = (j - r) % W
        outs.append(F.emit("xor2", [d[k], a[k]], "z%d" % j))
    xv = D0 ^ A0
    zv = veh.rotl32(xv, r)
    got = sum((1 if F.val[outs[j]] else 0) << j for j in range(W))
    F.outputs = outs
    F.toggle = set("s_a%d" % i for i in range(W))      # toggle the a word
    F.reference = dict(d=hex(D0), a=hex(A0), xor=hex(xv), want=hex(zv),
                       got=hex(got), MATCH=(got == zv))
    if cw_at_mean > 0.0 and mean > 0:
        for j, o in enumerate(outs):
            dd = abs(((j + r) % W) - j)
            dd = min(dd, W - dd)
            F.wire[o] = cw_at_mean * (dd / mean)
    return F


# --------------------------------------------------------------- flat deck
def flat_deck(F, vdd, tstep=200.0, tail=TAIL, wire=True, dv=1.65,
              halfcycle=1500.0):
    """PHASE 2 AMENDMENT B10.  Phase 1's OWN validated CMOS stimulus, adopted
    after my first version disagreed with itself.

    My first CMOS deck held the inputs and STEPPED THE SUPPLY, mirroring the QAL
    "settle-not-switch" rule.  Its 1 F energy integrator then returned
    -0.0673 fJ while its own V*Q cross-check returned +819.4 fJ -- opposite sign
    and 12000x the magnitude.  A number that disagrees with its own cross-check
    by four orders of magnitude cannot be used, and the disagreement is not a
    sign convention: with the supply ramping, part of the charge is delivered at
    V < vdd, so no single-voltage V*Q identity exists to check the integrator
    against in the first place.

    Phase 1's micro-harness did it the other way and validated it: the CMOS
    supply is HELD CONSTANT and the INPUTS are driven through a full cycle.
    Then, with V constant, the supply energy is EXACTLY

        E = vdd * (Q(end) - Q(0))

    which is convention-free in the sense gate G5 requires -- it needs no
    integrator and no sign convention, only a charge difference at a fixed
    voltage.  Phase 1 confirmed this harness reproduces the textbook
    n*Cw*vdd^2 per cycle to 0.4-0.6 % at five voltages.

    A full 0 -> 1 -> 0 cycle is also the right event to compare against a QAL
    beat, which RAISES the rail and RETURNS it: both are one complete
    charge-and-discharge of the datapath.  Each input therefore starts at its
    FINAL value, goes to its complement at t1, and returns to its final value at
    t2, so the deck ends in the state the value check expects.
    """
    t1 = tstep
    # AMENDMENT B10b: the half-cycle must be long enough for the SLOW direction
    # to finish.  MEASURED: at the G9-matched supply of 1.10 V the PDK xor2's
    # pull-up is a 2-HIGH pMOS stack with only 1.10 - 0.4403 = 0.66 V of
    # overdrive, and a rising output loaded by CL + rotate wire (9.767 fF) was
    # still at 0.639 V of 1.10 V after 196 ps.  A 200 ps half-cycle found no
    # valid instant at all and reported the delay as None.  The half-cycle is
    # widened to 1500 ps.  This is not a QAL/CMOS asymmetry: it is the same
    # low-swing penalty gate G9 imposes on the CMOS side by construction, and
    # measuring it properly is the point.
    t2 = tstep + halfcycle
    L = head_lines()
    L.append("VDD vdd 0 %g" % vdd)            # CONSTANT -- the whole point
    L.append("VGNDM gnm 0 0")
    tog = getattr(F, "toggle", set())
    for n in sorted(F.sources):
        hi = dv if F.sources[n] else 0.0
        if n not in tog:
            L.append("VS_%s %s 0 %g" % (n[2:], n, hi))      # HELD
            continue
        lo = 0.0 if F.sources[n] else dv
        L.append("VS_%s %s 0 PWL(0 %g %gp %g %gp %g %gp %g %gp %g)"
                 % (n[2:], n, hi, t1, hi, t1 + EDGE, lo, t2, lo, t2 + EDGE, hi))
    for idx, (kind, out, ins, sig) in enumerate(F.cells):
        L.append("X%s%d %s %s vdd gnm %s"
                 % (kind.upper(), idx, out, " ".join(ins), CELLS[kind][0]))
        L.append("CL%d %s gnm %gf" % (idx, out, CLOAD))
        cw = F.wire.get(out, 0.0) if wire else 0.0
        if cw > 0.0:
            L.append("CW%d %s gnm %.6ff" % (idx, out, cw))
    L += integ("qvdd", "-I(VDD)")
    tend = t2 + EDGE + tail
    L.append(".tran 0.1p %gp 0 0.25p" % tend)
    g = lambda t: t + LAG_PS
    for nm, tt in (("Z", 0.5), ("A", t1), ("B", t2), ("D", tend - 5.0)):
        L.append(".measure tran QVDD_%s FIND V(xqvdd) AT=%.6fp" % (nm, g(tt)))
    for o in F.outputs:
        L.append(".measure tran M_%s FIND V(%s) AT=%.6fp" % (o, o, g(tend - 5.0)))
        L.append(".measure tran C_%s FIND V(%s) AT=%.6fp" % (o, o, g(t2 - 5.0)))
    L.append(".print tran V(vdd) I(VDD) V(xqvdd) "
             + " ".join("V(%s)" % o for o in F.outputs))
    L.append(".end")
    return L, dict(vdd=vdd, tstep=tstep, t1=t1, t2=t2, tend=tend)


def flat_from_chain(ch):
    """Convert a cg.Chain into a Flat with the IDENTICAL cells, IDENTICAL wire
    and IDENTICAL held sources, discarding only the LEVEL structure -- which is
    a QAL scheduling constraint and has no meaning for CMOS.

    This is the gate-G9-strict comparator: the forwarding cells are still there,
    so only the technology differs.  Routing it through the same flat_deck() as
    the CMOS-native form guarantees the two CMOS variants are generated
    identically and differ only in which netlist they carry.
    """
    F = Flat("flat_" + ch.name)
    F.sources = dict(ch.sources)
    F.val = dict(ch.sources)
    netmap = {}
    for k in range(1, ch.nb + 1):
        for i, c in enumerate(ch.levels[k - 1]):
            ins = []
            for sname in c.ins:
                ins.append(netmap.get(sname, sname))
            out = F.emit(c.kind, ins, c.name)
            netmap[ch.out_net(k, i)] = out
            cw = ch.wire.get((k, i), 0.0)
            if cw > 0.0:
                F.wire[out] = cw
    F.outputs = [netmap[ch.out_net(ch.nb, i)] for i in range(ch.n_of(ch.nb))]
    # the flat netlist must reproduce the chain's own evaluated values
    bad = 0
    for k in range(1, ch.nb + 1):
        for i, c in enumerate(ch.levels[k - 1]):
            if bool(F.val[netmap[ch.out_net(k, i)]]) != bool(c.val):
                bad += 1
    F.chain_agreement = dict(mismatches=bad, cells=len(F.cells), PASS=(bad == 0))
    return F


def structural_table(W=32):
    """DERIVED, from the netlists themselves: the QAL-form and CMOS-form cost of
    the SAME two adder functions.  No simulation."""
    import veh
    out = {}
    for form in ("ks", "ripple"):
        q = veh.build_adder(W, form)
        c = cmos_adder(W, form)
        qc = q.census()
        cc = c.census()
        out[form] = dict(
            QAL_levels=q.nb, QAL_cells=qc["cells_total"],
            QAL_devices=qc["devices_total"],
            CMOS_cells=cc["cells"], CMOS_devices=cc["devices"],
            CMOS_gate_depth_DERIVED=cc["gate_depth_DERIVED"],
            forwarding_tax_cells=qc["cells_total"] - cc["cells"],
            forwarding_tax_devices=qc["devices_total"] - cc["devices"],
            QAL_over_CMOS_devices=round(qc["devices_total"] /
                                        float(cc["devices"]), 4),
            reference_MATCH=c.reference["MATCH"])
    out["_ratios"] = dict(
        QAL_ripple_over_ks_levels=round(out["ripple"]["QAL_levels"] /
                                        float(out["ks"]["QAL_levels"]), 4),
        QAL_ripple_over_ks_devices=round(out["ripple"]["QAL_devices"] /
                                         float(out["ks"]["QAL_devices"]), 4),
        CMOS_ripple_over_ks_devices=round(out["ripple"]["CMOS_devices"] /
                                          float(out["ks"]["CMOS_devices"]), 4),
        CMOS_ripple_over_ks_depth=round(out["ripple"]["CMOS_gate_depth_DERIVED"] /
                                        float(out["ks"]["CMOS_gate_depth_DERIVED"]), 4))
    return out


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "table":
        W = int(sys.argv[2]) if len(sys.argv) > 2 else 32
        t = structural_table(W)
        print(json.dumps(t, indent=1))
        sys.exit(0)
    if len(sys.argv) > 1 and sys.argv[1] == "check":
        for W in (8, 32):
            for form in ("ks", "ripple"):
                F = cmos_adder(W, form)
                c = F.census()
                print("  cmos %-6s w%-2d cells=%4d dev=%5d depth=%2d  ref %s"
                      % (form, W, c["cells"], c["devices"],
                         c["gate_depth_DERIVED"],
                         "MATCH" if F.reference["MATCH"] else
                         "MISMATCH %x vs %x" % (F.reference["got"],
                                                F.reference["want"])))
        F = cmos_addroundkey()
        c = F.census()
        print("  cmos addroundkey cells=%d dev=%d depth=%d  ref %s"
              % (c["cells"], c["devices"], c["gate_depth_DERIVED"],
                 "MATCH" if F.reference["MATCH"] else "MISMATCH"))
        sys.exit(0)
    print(__doc__)
